### ISSUE TITLE
POMCPOW in VDPTag

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [zsunberg/VDPTag2.jl#5]
Hey @zsunberg, could you explain where POMCPOW is integrated into VDPTag2? I'm having trouble figuring out where the solver is being defined inside VDPTag2.

**Comment by zsunberg** [comment]
They are separate packages, and the integration is only through the POMDPs.jl interface. Does that make sense?

If you are just trying to get it to run, I think if you run the example on the POMCPOW readme, https://github.com/JuliaPOMDP/POMCPOW.jl#usage, and just replace BabyPOMDP with VDPTagPOMDP, it should work.

**Comment by ChandlerKilpatrick1** [comment]
So if I'm understand what you're saying correctly, when I run `runtest.jl` in VDPTag2, it's not actually solving the problem using POMCPOW but rather a heuristic that you wrote in `heuristics.jl`?

**Comment by zsunberg** [comment]
Yeah, exactly!

**Comment by ChandlerKilpatrick1** [comment]
Thanks!
