### ISSUE TITLE
Where is the rand(rng, Bool) function defined? 

### ISSUE THREAD

**Issue by logankilpatrick** [zsunberg/VDPTag2.jl#8]
Hey Zach, where is the rand function defined for the 2nd rand call in this function: https://github.com/zsunberg/VDPTag2.jl/blob/9e219a05c75cc1e37dc9021ad3f098cc912e166f/src/VDPTag2.jl#L123 ?

I don't see where `rand(rng, Bool)` is defined anywhere.  I am getting an error saying that the Sampler for that object is not defined but I don't know where to wrap that function since I don't see it in the code.

**Comment by zsunberg** [comment]
That is a really strange error - `rand(rng, Bool)` should be defined in the julia base Random module. On my machine:

![Screenshot from 2020-04-25 08-37-51](https://user-images.githubusercontent.com/4240491/80282675-1b720c00-86d0-11ea-936f-f2841277349a.png)

Maybe check your julia version and Pkg.status() and post the error and maybe we can figure out what it is.

**Comment by logankilpatrick** [comment]
Resolved
